In [97]:
import pandas as pd
df = pd.read_csv('E:/MY_WORK/WEEK_2/seeds.csv')

In [83]:
df.head()

,Sr. No.,Area,Perimeter,Compactness,Kernel.Length,Kernel.Width,Asymmetry.Coeff,Kernel.Groove,Type
0,1,15.55,12.22,0.8888,5.763,3.312,NaN,NaN,1
1,2,14.88,NaN,0.8811,5.554,3.333,1.018,4.956,1
2,3,14.29,14.12,0.1111,5.544,NaN,2.699,4.825,1
3,4,13.84,13.94,NaN,6.544,NaN,2.259,4.805,1
4,4,13.84,13.94,0.8955,5.550,NaN,2.259,4.805,1

In [84]:
df.info

<bound method DataFrame.info of      Sr. No.   Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0          1  15.55      12.22       0.8888          5.763         3.312
1          2  14.88        NaN       0.8811          5.554         3.333
2          3  14.29      14.12       0.1111          5.544           NaN
3          4  13.84      13.94          NaN          6.544           NaN
4          4  13.84      13.94       0.8955          5.550           NaN
..       ...    ...        ...          ...            ...           ...
196      195  12.19      13.20       0.8783          5.137         2.981
197      196  11.23      12.88       0.8511          5.140         2.795
198      197  13.20      13.66       0.8883          5.236         3.232
199      198  11.84      13.21       0.8521          5.175         2.836
200      199  12.30      13.34       0.8684          5.243         2.974

    Asymmetry.Coeff  Kernel.Groove  Type
0               NaN            NaN     1
1             1.018          4.956     1
2             2.699          4.825     1
3             2.259          4.805     1
4             2.259          4.805     1
..              ...            ...   ...
196           3.631          4.870     3
197           4.325          5.003     3
198           8.315          5.056     3
199           3.598          5.044     3
200           5.637          5.063     3

[201 rows x 9 columns]>

In [85]:
df.describe()

,Sr. No.,Area,Perimeter,Compactness,Kernel.Length,Kernel.Width,Kernel.Groove,Type
count,201.000000,201.000000,200.000000,197.000000,200.000000,197.000000,198.000000,201.000000
mean,99.084577,14.909701,14.576850,0.866716,5.649395,3.262751,5.413939,1.985075
std,58.029801,2.907479,1.319096,0.058882,0.446056,0.379555,0.496329,0.815338
min,1.000000,10.590000,12.220000,0.111100,4.899000,2.630000,4.519000,1.000000
25%,49.000000,12.360000,13.467500,0.856400,5.267000,2.953000,5.045000,1.000000
50%,99.000000,14.380000,14.285000,0.873400,5.544500,3.232000,5.226000,2.000000
75%,149.000000,17.360000,15.782500,0.886600,6.008750,3.566000,5.878500,3.000000
max,199.000000,21.180000,17.250000,0.918300,6.675000,4.033000,6.550000,3.000000

In [86]:
df.shape

(201, 9)

In [87]:
#Data Cleaning
duplicate_row = df[df.duplicated()]
print(f"Number of Duplicate Rows{len(duplicate_row)}")#number of duplicate
print("*"*100+"\n")

print(duplicate_row)#print row

Number of Duplicate Rows1
****************************************************************************************************

    Sr. No.   Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
20       12  13.89      14.02        0.888          5.439         3.199

   Asymmetry.Coeff  Kernel.Groove  Type
20           3.986          4.738     1

In [88]:
# Remove duplicate value
df.drop_duplicates(inplace = True)
df.shape

(200, 9)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 200
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sr. No.          200 non-null    int64
 1   Area             200 non-null    float64
 2   Perimeter        199 non-null    float64
 3   Compactness      196 non-null    float64
 4   Kernel.Length    199 non-null    float64
 5   Kernel.Width     196 non-null    float64
 6   Asymmetry.Coeff  198 non-null    object
 7   Kernel.Groove    197 non-null    float64
 8   Type             200 non-null    int64
dtypes: float64(6), int64(2), object(1)
memory usage: 15.6+ KB

In [90]:
# Conver int data into float
df["Type"] = df["Type"].astype(float)
df.head()

,Sr. No.,Area,Perimeter,Compactness,Kernel.Length,Kernel.Width,Asymmetry.Coeff,Kernel.Groove,Type
0,1,15.55,12.22,0.8888,5.763,3.312,NaN,NaN,1.0
1,2,14.88,NaN,0.8811,5.554,3.333,1.018,4.956,1.0
2,3,14.29,14.12,0.1111,5.544,NaN,2.699,4.825,1.0
3,4,13.84,13.94,NaN,6.544,NaN,2.259,4.805,1.0
4,4,13.84,13.94,0.8955,5.550,NaN,2.259,4.805,1.0

In [91]:
# Normalizing Data (Example: Scaling scores between 0 and 1)
df["Type"] = df["Type"]/10
df

,Sr. No.,Area,Perimeter,Compactness,Kernel.Length,Kernel.Width,Asymmetry.Coeff,Kernel.Groove,Type
0,1,15.55,12.22,0.8888,5.763,3.312,NaN,NaN,0.1
1,2,14.88,NaN,0.8811,5.554,3.333,1.018,4.956,0.1
2,3,14.29,14.12,0.1111,5.544,NaN,2.699,4.825,0.1
3,4,13.84,13.94,NaN,6.544,NaN,2.259,4.805,0.1
4,4,13.84,13.94,0.8955,5.550,NaN,2.259,4.805,0.1
...,...,...,...,...,...,...,...,...,...
196,195,12.19,13.20,0.8783,5.137,2.981,3.631,4.870,0.3
197,196,11.23,12.88,0.8511,5.140,2.795,4.325,5.003,0.3
198,197,13.20,13.66,0.8883,5.236,3.232,8.315,5.056,0.3
199,198,11.84,13.21,0.8521,5.175,2.836,3.598,5.044,0.3
200,199,12.30,13.34,0.8684,5.243,2.974,5.637,5.063,0.3

In [92]:
# Handling missing value
# Check for missing values in each column
Column_missing_value = df.isnull().sum()
print("*"*100)
print(Column_missing_value)

# Check for missing values in each rows
row_missing_value = df[df.isnull().any(axis=1)]
print("*"*100)
print(row_missing_value)

# Check Missing value in a specific column
missing_values_in_column = df['Compactness'].isnull().sum()
print("*"*100)
print('Missing values in Compactness are :',missing_values_in_column)

****************************************************************************************************
Sr. No.            0
Area               0
Perimeter          1
Compactness        4
Kernel.Length      1
Kernel.Width       4
Asymmetry.Coeff    2
Kernel.Groove      3
Type               0
dtype: int64
****************************************************************************************************
     Sr. No.   Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0          1  15.55      12.22       0.8888          5.763         3.312
1          2  14.88        NaN       0.8811          5.554         3.333
2          3  14.29      14.12       0.1111          5.544           NaN
3          4  13.84      13.94          NaN          6.544           NaN
4          4  13.84      13.94       0.8955          5.550           NaN
5          5  16.14      14.99       0.9034          5.658           NaN
6          6  14.38      14.21          NaN          5.386         3.312
15        15  14.59      14.28          NaN          5.351         3.333
25        24  15.01      14.76          NaN          5.789         3.245
47        46  14.99      14.56       0.8883            NaN         3.377
50        49  14.43      14.40       0.8751          5.585         3.272
85        84  18.98      16.66       0.8590          6.549         3.670
104      103  17.63      15.86       0.8800          6.033         3.573

    Asymmetry.Coeff  Kernel.Groove  Type
0               NaN            NaN   0.1
1             1.018          4.956   0.1
2             2.699          4.825   0.1
3             2.259          4.805   0.1
4             2.259          4.805   0.1
5             1.355          5.175   0.1
6             2.462          4.956   0.1
15            4.185          4.781   0.1
25            1.791          5.001   0.1
47            2.958          5.175   0.1
50            3.975            NaN   0.1
85              NaN          6.498   0.2
104           3.747            NaN   0.2
****************************************************************************************************
Missing values in Compactness are : 4

In [93]:
# Drop all missing values
df.dropna(inplace = True)
df.isnull().sum()# 9 rows deleted because missing value 
df.shape

(187, 9)

In [96]:
# df.head(50)

# Missing values deleted
Column_missing_value = df.isnull().sum()
print("*"*100)
print(Column_missing_value)

****************************************************************************************************
Sr. No.            0
Area               0
Perimeter          0
Compactness        0
Kernel.Length      0
Kernel.Width       0
Asymmetry.Coeff    0
Kernel.Groove      0
Type               0
dtype: int64